// ============================================================
// Build-time version generator
// ------------------------------------------------------------
// Writes src/app/core/version.ts with real build metadata (app
// version, build number, build date, git commit, framework
// versions). Wired into the npm pre* hooks so it runs before
// every `start` / `build` / `watch`.
//
// Robust by design: every lookup falls back to a safe default,
// so the build never fails if git is missing or a CI var is unset.
// ============================================================

import { execSync } from 'node:child_process';
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function readJSON(path) {
  try {
    return JSON.parse(readFileSync(join(root, path), 'utf8'));
  } catch {
    return {};
  }
}

function tryCmd(cmd, fallback) {
  try {
    return execSync(cmd, { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

// Prefer the actually-installed framework version; fall back to the
// declared range in package.json with the semver-range prefix stripped.
function installedVersion(pkg, declared) {
  const v = readJSON(`node_modules/${pkg}/package.json`).version;
  if (v) return v;
  return (declared || '').replace(/^[\^~>=<\s]+/, '') || 'unknown';
}

const pkg = readJSON('package.json');
const deps = { ...pkg.dependencies, ...pkg.devDependencies };

const version = pkg.version || '0.0.0';
const commit = tryCmd('git rev-parse --short HEAD', 'local');
const branch = tryCmd('git rev-parse --abbrev-ref HEAD', 'local');
// CI build numbers, in order of preference; otherwise a local marker.
const buildNumber =
  process.env.BUILD_NUMBER ||
  process.env.GITHUB_RUN_NUMBER ||
  process.env.CI_PIPELINE_IID ||
  'local';

const info = {
  version,
  buildNumber: `${version}+${buildNumber}`,
  buildDate: new Date().toISOString(),
  commit,
  branch,
  angular: installedVersion('@angular/core', deps['@angular/core']),
  material: installedVersion('@angular/material', deps['@angular/material']),
};

const out = `// AUTO-GENERATED by scripts/generate-version.mjs — DO NOT EDIT.
// Regenerated on every start/build/watch. Not committed (see .gitignore).
export const BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;

export type BuildInfo = typeof BUILD_INFO;
`;

writeFileSync(join(root, 'src/app/core/version.ts'), out);
console.log(`[version] v${info.version} build ${info.buildNumber} (${info.commit}) @ ${info.buildDate}`);
